version: "3.8" # Versión de Docker Compose

services:
  database:
    image: mongo:latest
    container_name: mongo
    hostname: mongodb
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - database-network
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    restart: always

  mongo-express:
    depends_on:
      - database
    image: mongo-express
    container_name: my-mongo-express-container
    hostname: mongodb-express
    restart: always
    networks:
      - database-network
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_EXPRESS_URL}
      - ME_CONFIG_BASICAUTH=false

networks:
  database-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
